apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: llm-ingress-tls
  namespace: kourier-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vllm-phi2-predictor.llm-system.llm.local`)
      kind: Rule
      services:
        - name: kourier
          port: 80
    - match: Host(`vllm-dialogpt-predictor.llm-system.llm.local`)
      kind: Rule
      services:
        - name: kourier
          port: 80
  tls:
    secretName: llm-tls
