{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-certmanager
  namespace: knative-serving
  labels:
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/component: certmanager
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  issuerRef: |
    name: {{ .Values.certManager.issuers.externalDomain.name | quote }}
    kind: {{ .Values.certManager.issuers.externalDomain.kind | quote }}
  clusterLocalIssuerRef: |
    name: {{ .Values.certManager.issuers.clusterLocalDomain.name | quote }}
    kind: {{ .Values.certManager.issuers.clusterLocalDomain.kind | quote }}
  systemInternalIssuerRef: |
    name: {{ .Values.certManager.issuers.systemInternal.name | quote }}
    kind: {{ .Values.certManager.issuers.systemInternal.kind | quote }}
{{- end }}
